name: CI/CD Proyecto Empresa

on:
  push:
    branches:
      - main
      - dev
      - qa
      - 'feature/**'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (if available)
        run: |
          if [ -d tests ]; then
            pip install pytest
            pytest
          else
            echo "No hay tests"
          fi

      - name: Build (compile PY)
        run: python -m py_compile src/*.py
